name:                webgl-fundamentals-fp
version:             0.1.0.0
github:              "githubuser/webgl-fundamentals-fp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/webgl-fundamentals-fp#readme>

default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - StrictData
  - ExtendedDefaultRules
  - ScopedTypeVariables
  - QuasiQuotes

dependencies:
  - aeson
  - async
  - base
  - butcher
  - bytestring
  - hashable
  - hslogger
  - http-client
  - http-conduit
  - http-types
  - lucid
  - mtl
  - network
  - postgresql-simple
  - process
  - record-hasfield
  - retry
  - rio
  - scotty
  - serialise
  - stm
  - text
  - time
  - transformers
  - typed-process
  - wai-cors
  - wai-middleware-static
  - yaml

ghc-options:
  - -F -pgmF=record-dot-preprocessor

library:
  source-dirs: src

executables:
  webgl-fundamentals-fp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webgl-fundamentals-fp

tests:
  webgl-fundamentals-fp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webgl-fundamentals-fp
